### ISSUE TITLE
Investigate identifier value being negative

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#664] opened 2023-06-16 13:30 UTC
# Description

`starknet_getClass` returns the expected contract except that the member value in the identifiers in the program is positive for some numbers instead of being negative. This should be investigated and fixed eventually.

```json
 "starkware.cairo.common.bitwise.ALL_ONES": {
             "type": "const"
      -      "value": "3618502788666131106986593281521497120414687020801267626233049500247285301247"
      +      "value": "-106710729501573572985208420194530329073740042555888586719234"
           }
```
The get class test should pass with this line uncommented:
```js
// expect(program).to.deep.equal(ERC20_CONTRACT.program);
```

**Comment by abdelhamidbakhta** [comment] 2023-06-20 08:25
> I can take this.

Assigned to you

**Comment by abdelhamidbakhta** [comment] 2023-07-04 07:57
> I can take this.

Removed you the assignment since no sign of activity since 2 weeks

**Comment by gylman** [comment] 2023-07-26 02:01
I would like to take this.

**Comment by abdelhamidbakhta** [comment] 2023-07-26 04:50
> 

Let’s go

**Comment by gylman** [comment] 2023-07-28 01:54
The RPC server returns positive number for the `value`. The issue is not related to Rust code. The issue is related to cairo compilation. I recompiled the cairo contracts and indeed, the exact negative value appears there. 
![Screenshot 2023-07-28 at 10 48 17 AM](https://github.com/keep-starknet-strange/madara/assets/76925587/08fd0a57-3635-458d-84a0-255a4d7632a7)
I attach the image. [](url)

**Comment by LucasLvy** [comment] 2023-07-28 09:38
Ah indeed the issue looks to be inverted. So this idea now is to return a negative number where it should negative. We consider the compiled contract as the source of truth, we need to modify the rpc so it sends the exact replica of the compiled contract.
Does that help you ? (i'm modifying the issue so it corresponds to the relaity)

**Comment by gylman** [comment] 2023-07-28 10:37
Yes, thank you, I will dig further

**Comment by gylman** [comment] 2023-08-02 02:04
### **Current status**

```
let json_str = &read_file_to_string("../../cairo-contracts/build/ERC20.json");
    println!("test1:   {:?}", json_str); 
// property: program.identifiers["starkware.cairo.common.bitwise.ALL_ONES"]
// value is negative: "-106710729501573572985208420194530329073740042555888586719234"

let test: ContractClassV0 = serde_json::from_str(json_str.as_str()).unwrap();
    println!("test2:   {:?}", test); 
// property: program.identifiers["starkware.cairo.common.bitwise.ALL_ONES"]
// value is positive: "3618502788666131106986593281521497120414687020801267626233049500247285301247"
```

The value for the `"starkware.cairo.common.bitwise.ALL_ONES"` is negative(*expected*) in `json_str` , but positive, once it is returned into `test`

`serde_program` defines `deserialize` that calls `deserialize` of `ProgramJson`

```rust
mod serde_program {
    use super::*;

    /// Serializes the Program using the ProgramJson
    pub fn serialize<S: Serializer>(program: &Program, serializer: S) -> Result<S::Ok, S::Error> {
        let program = parse_program(program.clone());
        program.serialize(serializer)
    }

    /// Deserializes the Program using the ProgramJson
    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Program, D::Error> {
        let prog = ProgramJson::deserialize(deserializer)?;
        parse_program_json(prog, None)
            .map_err(|e| de::Error::custom(format!("couldn't convert programjson to program {e:}")))
    }
}
```

```rust
pub struct ProgramJson {
    pub prime: String,
    pub builtins: Vec<BuiltinName>,
    #[serde(
        deserialize_with = "deserialize_array_of_bigint_hex",
        serialize_with = "serialize_program_data"
    )]
    pub data: Vec<MaybeRelocatable>,
    pub identifiers: HashMap<String, Identifier>,
    pub hints: HashMap<usize, Vec<HintParams>>,
    pub reference_manager: ReferenceManager,
    pub attributes: Vec<Attribute>,
    pub debug_info: Option<DebugInfo>,
    pub main_scope: String,
    pub compiler_version: String,
}
```

The following is the structure of the `Identifier` generic parameter

```rust
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct Identifier {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pc: Option<usize>,
    #[serde(
        rename(deserialize = "type", serialize = "type"),
        skip_serializing_if = "Option::is_none"
    )]
    pub type_: Option<String>,
    #[serde(default)]
    #[serde(
        deserialize_with = "felt_from_number",
        serialize_with = "number_from_felt",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Felt252>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub members: Option<HashMap<String, Member>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cairo_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decorators: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub references: Option<Vec<Reference>>,
}
```

The `value` property is of type `Felt225` which is:

```rust
pub struct Felt252 {
    value: FeltBigInt<FIELD_HIGH, FIELD_LOW>,
}
```

and `FeltBigInt` returns `BigUint` which cannot possibly return the negative value, which we want

```rust
pub(crate) struct FeltBigInt<const PH: u128, const PL: u128> {
    val: BigUint,
}
```

Changing `BigUint` to `BigInt` had no effect on the displayed value, in fact I made purposeful errors in file and the compilation was still successful, which means the file is not compiled and the value is possibly from cache? Could you let me know if I am going in the correct direction?

**Comment by tdelabro** [comment] 2023-08-11 10:14
@gylman What is the status on this one. Is the bug still there?

**Comment by gylman** [comment] 2023-08-11 10:16
@tdelabro yes, the bug is still there, because we do not know if the conclusions are correct

**Comment by gylman** [comment] 2023-08-11 11:11
@tdelabro did you check my question? can anyone from madara team give feedback about it?

**Comment by tdelabro** [comment] 2023-08-11 11:36
I did but I don't have a quick answer to give you. I don't know better than you on this one.

How can we help you pursue your research?

**Comment by gylman** [comment] 2023-08-11 14:07
If you do not know, then I will work on it one more week, and then I let you know whether I keep continue or drop it.

**Comment by tdelabro** [comment] 2023-08-17 15:30
@gylman Thanks a lot !!

**Comment by gylman** [comment] 2023-08-21 09:26
@tdelabro do not unassign yet please, still working, getting closer

**Comment by tdelabro** [comment] 2023-08-24 12:02
@gylman do you think it can be the same problem as  #1033 is fixing?

**Comment by gylman** [comment] 2023-08-24 14:20
@tdelabro I will post the exact problem in the upcoming 24 hours. The issue is related to Cairo Felt.

**Comment by ptisserand** [comment] 2023-08-24 15:33
> @gylman do you think it can be the same problem as #1033 is fixing?

With #1033 applied, the value is still wrong in program retrieved by `getClassAt`

**Comment by gylman** [comment] 2023-08-25 08:01
@tdelabro It is not possible to get negative values (what we need) with felt_str!:
<img width="916" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/76925587/813e066d-096c-4660-abd9-107da434a4f1">

**Comment by tdelabro** [comment] 2023-08-25 08:08
Oooh. But are we using `felt_str!`? I don't find it in the project

**Comment by tdelabro** [comment] 2023-08-25 08:08
What should we do then?

**Comment by gylman** [comment] 2023-08-25 08:22
@tdelabro here is more detailed description:

# Madara FeltBigInt issue

Person in charge: gylman
Writer: gylman
Created Date: August 25, 2023 5:08 PM

![Untitled](Madara%20FeltBigInt%20issue%20497ec9b0283e44ef8fa484b109901547/Untitled.png)

The type of the value returned from `felt_str!` is `Felt252`

![Untitled](Madara%20FeltBigInt%20issue%20497ec9b0283e44ef8fa484b109901547/Untitled%201.png)

The type of the `value` is `FeltBigInt`

![Untitled](Madara%20FeltBigInt%20issue%20497ec9b0283e44ef8fa484b109901547/Untitled%202.png)

The type of the `value` is `BigUint`

So, it we cannot have negative values. It should be implemented using `BigInt` but then all the code has to be changed.

So, should I do it, despite it is not a Madara issue, or should [cairo-vm](https://github.com/lambdaclass/cairo-vm) team do it?

**Comment by gylman** [comment] 2023-08-25 08:30
@tdelabro you will find it here:

<img width="986" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/76925587/85e1cce4-7ca0-46c2-8c37-8def625ae2a4">

**Comment by gylman** [comment] 2023-08-25 08:39
Regardless of the process, the end conclusion is the identifier value is of type `Felt252` which is implemented using `BigUint` which covers only positive values.

**Comment by tdelabro** [comment] 2023-08-27 15:17
Okay. I'm investigating what can be done with lambdaclass

**Comment by gylman** [comment] 2023-08-27 20:36
@tdelabro thanks for the update

**Comment by tdelabro** [comment] 2023-08-28 16:46
@gylman 
After some investigation it appears that those two values are the same. 
`3618502788666131106986593281521497120414687020801267626233049500247285301247` is just the positive representation of `-106710729501573572985208420194530329073740042555888586719234` wrapped around itself. 
Both are equal to https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/bitwise.cairo#L3.

What happens is that during the deserialization is that `felt_from_number` is called for the value field, in turn it call `Felt252::parse_bytes` which impl is the following:
```rust
    fn parse_bytes(buf: &[u8], radix: u32) -> Option<FeltBigInt<FIELD_HIGH, FIELD_LOW>> {
        match BigUint::parse_bytes(buf, radix) {
            Some(parsed) => Some(FeltBigInt::new(parsed)),
            None => BigInt::parse_bytes(buf, radix).map(FeltBigInt::new),
        }
    }
```

which end up calling this one:
```rust
impl<const PH: u128, const PL: u128> From<&BigInt> for FeltBigInt<PH, PL> {
    fn from(value: &BigInt) -> Self {
        Self {
            val: value
                .mod_floor(&CAIRO_SIGNED_PRIME)
                .to_biguint()
                .expect("mod_floor is always positive"),
        }
    }
}
```
which by calling `mod_floor(&CAIRO_SIGNED_PRIME)` ensure the conversion to a positive number.

So everything work perfectly. The only thing we have to do is to compare felts rather than comparing strings in our tests.
It should be taken care of with the tests being rewritten in rust. The strong typing will take care of it

**Closed by tdelabro** 2023-08-28 16:46 UTC
Labels: bug, good first issue, backlog

**Comment by gylman** [comment] 2023-08-29 01:26
@tdelabro thank you for the update, interesting
